title: Amaris Nissi
description: Aerospace Engineer
site_title: '@amaris-nissi'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: amaris-nissi
# blog_url: https://www.nagekar.com
email: amarisnissi@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp2.jpg

# Google Analytics ID
google_analytics: 